import moment from 'moment';
export default {
    tasks: [
        {
            id: 1,
            projectId: 1,
            projectDependencyIds: [],
            taskDependencyIds: [],
            childTaskIds: [],
            parentTaskId: null,
            serviceIds: [],
            expectedHours: 1,
            workedHours: 0,
            title: "Init Project",
            description: "Create Github and general structure",
            dueAt: moment().format('X'),
            createdAt: moment().format('X')
        },
        {
            id: 2,
            projectId: 1,
            projectDependencyIds: [],
            taskDependencyIds: [],
            childTaskIds: [],
            parentTaskId: null,
            serviceIds: [],
            expectedHours: 1,
            workedHours: 0,
            title: "Create Database",
            description: "Choose and integrate app db",
            dueAt: moment().format("X"),
            createdAt: moment().format('X')
        },
        {
            id: 3,
            projectId: 2,
            projectDependencyIds: [],
            taskDependencyIds: [],
            childTaskIds: [],
            parentTaskId: null,
            serviceIds: [],
            expectedHours: 1,
            workedHours: 0,
            title: "Contact Rep",
            description: "Contact Rep at Institution",
            dueAt: moment().format("X"),
            createdAt: moment().format('X')
        },
        {
            id: 4,
            projectId: 1,
            projectDependencyIds: [],
            taskDependencyIds: [],
            childTaskIds: [6],
            parentTaskId: null,
            serviceIds: [],
            expectedHours: 1,
            workedHours: 0,
            title: "Create GUI",
            description: "Create layout components and ui interface",
            dueAt: moment().format("X"),
            createdAt: moment().format('X')
        },
        {
            id: 5,
            projectId: 2,
            projectDependencyIds: [],
            taskDependencyIds: [],
            childTaskIds: [],
            parentTaskId: null,
            serviceIds: [],
            expectedHours: 1,
            workedHours: 0,
            title: "Send Documents to Rep",
            description: "Collect necessary dox and forward to Rep",
            dueAt: moment().format("X"),
            createdAt: moment().format('X')
        },
        {
            id: 6,
            projectId: 1,
            projectDependencyIds: [],
            taskDependencyIds: [],
            childTaskIds: [],
            parentTaskId: 4,
            serviceIds: [],
            expectedHours: 1,
            workedHours: 0,
            title: "Stylize",
            description: "Add CSS To GUI",
            dueAt: moment().format("X"),
            createdAt: moment().format('X')
        },
    ]
}
